# This playbook will intall a PHP application on virtual machines running CentOS7 and then install an HAProxy LB
- name: install web application
  hosts: web
  gather_facts: yes
  become: true

  vars_files:
    - ./vars/general_vars.yml

  tasks:
  - name: configure hostname to match VM name
    hostname:
       name: "{{ inventory_hostname }}.acme.com"

  - name: add hostname to /etc/hosts
    lineinfile:
       dest: /etc/hosts
       regexp: '^127\.0\.0\.1[ \t]+localhost'
       line: "127.0.0.1 localhost {{ inventory_hostname }}"

  roles:
  - { role: "install-app" }

- name: install load balancer with keepalive
  hosts: frontend
  gather_facts: yes
  become: true

  vars:
    k_master_ip: "12.12.1.15"
    k_slave_ip: "12.12.1.20"
    k_vip: "12.12.1.110"

  vars_files:
    - ./vars/general_vars.yml
  
  tasks:
  - name: configure hostname to match VM name
    hostname:
       name: "{{ inventory_hostname }}.acme.com"

  - name: add hostname to /etc/hosts
    lineinfile:
       dest: /etc/hosts
       regexp: '^127\.0\.0\.1[ \t]+localhost'
       line: "127.0.0.1 localhost {{ inventory_hostname }}"

  roles:
  - { role: "haproxy" }
  - { role: "haproxy-keepalived", master_ip: "{{ k_master_ip }}", slave_ip: "{{ k_slave_ip }}", virtual_ip: "{{ k_vip }}", is_master: "{{ master }}", if_name: "{{ int_name }}" }

