---
- name: configure basic CentOS host settings
  hosts: web
  gather_facts: yes
  become: true

  vars_files: 
    - ./vars/general_vars.yml
  
  tasks:
    - name: configure hostname to match VM name
      hostname: 
         name: "{{ inventory_hostname }}.acme.com"

    - name: add hostname to /etc/hosts
      lineinfile:
         dest: /etc/hosts
         regexp: '^127\.0\.0\.1[ \t]+localhost'
         line: "127.0.0.1 localhost {{ inventory_hostname }}"
