# This playbook will intall a PHP application on virtual machines running CentOS7 and then install an HAProxy LB
- name: install web application
  hosts: web-vm
  gather_facts: yes
  become: true

  vars_files:
    - ./vars/general_vars.yml
    - ./vars/vcenter-info.yml

  roles:
  - { role: "install-app" }

- name: install load balancer with keepalive
  hosts: haproxy
  gather_facts: yes
  become: true

  vars:
    k_master_ip: "10.40.40.101"
    k_slave_ip: "10.40.40.102"
    k_vip: "10.40.40.110"

  vars_files:
    - ./vars/general_vars.yml
    - ./vars/vcenter-info.yml

  roles:
  - { role: "haproxy" }
  - { role: "haproxy-keepalived", master_ip: "{{ k_master_ip }}", slave_ip: "{{ k_slave_ip }}", virtual_ip: "{{ k_vip }}", is_master: "{{ master }}" }

