--- 
- name: Configure Tenant and Application Profile for Acme
  hosts: apic-troy-1
  connection: local
  gather_facts: no

  vars_files:
    - ./vars/general_vars.yml

  roles: 
  - { role: "create-acme-networks" }
  - { role: "base-contracts" }
  - { role: "create-acme-ap" }

- name: Launch a LB
  hosts: haproxy
  gather_facts: no
  connection: local

  vars_files:
    - ./vars/general_vars.yml
    - ./vars/vcenter-info.yml

  roles: 
  - { role: "clone-vm-vmware", ip_address: "{{ ansible_host }}", ip_gateway: "{{ server_bd_subnet }}", dvportgroup_name: "{{ tenant_name}}|AcmeNetworks|ServerNetwork" }

- name: Launch the web server VMs
  hosts: web-vm
  gather_facts: no
  connection: local

  vars_files:
    - ./vars/general_vars.yml
    - ./vars/vcenter-info.yml

  roles:
  - { role: "clone-vm-vmware", ip_address: "{{ ansible_host }}", ip_gateway: "{{ server_bd_subnet }}", dvportgroup_name: "{{ tenant_name}}|AcmeNetworks|ServerNetwork" }

- name: Configure Application Profile and uEPG
  hosts: apic-troy-1
  connection: local
  gather_facts: no

  vars_files:
    - ./vars/general_vars.yml

  roles:
  - { role: "create-opencart-uepg", ap_name: "OpenCart-PROD" }
