--- 
- name: Configure Tenant and Application Profile for Acme
  hosts: apic-troy-1
  connection: local
  gather_facts: no

  vars_files:
    - ./vars/general_vars.yml

  roles: 
#  - { role: "base-contracts" }
#  - { role: "create-acme-networks" }
  - { role: "create-acme-ap" }
