---
- name: Import Virtual Machine from a vCenter
  hosts: web
  connection: local
  gather_facts: no

  vars_files: 
    - ./vars/general_vars.yml
  
  tasks:
    - block:
       - include_vars: ./vars/ovirt_data.yml

       - name: obtain SSO token with username and password credentials
         ovirt_auth:
            url: "{{ rhvm_url }}"
            username: admin@internal
            ca_file: ca.pem
            password: "{{ ovirt_password }}"

       - name: import VM from vCenter
         ovirt_vms:
            auth: "{{ ovirt_auth }}"
            name: "{{ inventory_hostname }}"
            state: present
            clone: yes
            cluster: "{{ rhv_cluster }}"
            vmware:
               url: "vpx://{{ vcenter }}/{{ vmw_dc }}/{{ vmw_cluster }}/{{ vmw_host_01 }}?no_verify=1"
               name: "{{ inventory_hostname }}"
               username: "{{ vcenter_user }}"
               password: "{{ vcenter_pass }}"
               storage_domain: "{{ rhv_storage_domain }}"

       - name: change VM NIC to new profile
         ovirt_nics:
            auth: "{{ ovirt_auth }}"
            vm: "{{ inventory_hostname }}"
            name: nic1
            profile: "{{ tenant_name }}|{{ ap_name }}|{{ epg_name }}"
            network: "{{ tenant_name }}|{{ ap_name }}|{{ epg_name }}"

       - name: boot up the VM
         ovirt_vms:
            auth: "{{ ovirt_auth }}"
            state: running
            name: "{{ inventory_hostname }}"
            type: server

      always:
       - name: revoke SSO token
         ovirt_auth:
            state: absent
            ovirt_auth: "{{ ovirt_auth }}"
